#项目启动端口,默认35080
server.port=35080
server.servlet.context-path=/

#修改默认的JSESSIONID为oauth2_session_id
server.servlet.session.cookie.name=oauth2_session_id

spring.thymeleaf.cache=false
spring.task.scheduling.pool.size=8

logging.level.root=info
#logging.level.org.springframework.security=debug
#logging.level.org.hibernate=trace
logging.file.path=/data/logs/oauth2-server
logging.logback.rollingpolicy.max-history=60

server.tomcat.accesslog.directory=/data/logs/oauth2-server
server.tomcat.accesslog.enabled=true
server.tomcat.accesslog.rename-on-rotate=true

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

spring.datasource.url=jdbc:postgresql://localhost:5432/oauth2_server?createDatabaseIfNotExist=true&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
spring.datasource.username=postgres
spring.datasource.password=P@ssw0rd
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.max-lifetime=1800000

spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
spring.jpa.show-sql=false
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

signin.failure.max=5
#signIn是否启用图形验证码
signIn.captcha=false
#oauth2 issuer
#验证码最大尝试次数
captcha.max.times=5

thirdparty.weixin.mini.appid=
thirdparty.weixin.mini.secret=

captcha.prefix=captcha
captcha.expire.default=120000
captcha.expire.WORD_IMAGE_CLICK=180000
captcha.init-default-resource=true
captcha.local-cache-enabled=true
captcha.cache.cache-size=20
captcha.local-cache-wait-time=5000
captcha.local-cache-period=120000
captcha.secondary.enabled=false
captcha.expire=120000
captcha.keyPrefix=captcha:secondary

